$primary_paletteKeyColor = 897627
$secondary_paletteKeyColor = 807757
$tertiary_paletteKeyColor = 5c7f65
$neutral_paletteKeyColor = 7c776b
$neutral_variant_paletteKeyColor = 7c7767
$background = 16130b
$onBackground = e9e2d4
$surface = 16130b
$surfaceDim = 16130b
$surfaceBright = 3c392f
$surfaceContainerLowest = 100e07
$surfaceContainerLow = 1e1b13
$surfaceContainer = 221f17
$surfaceContainerHigh = 2d2a21
$surfaceContainerHighest = 38352b
$onSurface = e9e2d4
$surfaceVariant = 4b4739
$onSurfaceVariant = cdc6b4
$inverseSurface = e9e2d4
$inverseOnSurface = 333027
$outline = 979080
$outlineVariant = 4b4739
$shadow = 000000
$scrim = 000000
$surfaceTint = ddc66e
$primary = ddc66e
$onPrimary = 3a3000
$primaryContainer = 544600
$onPrimaryContainer = fae287
$inversePrimary = 6f5d0e
$secondary = d2c6a1
$onSecondary = 373016
$secondaryContainer = 51492c
$onSecondaryContainer = efe2bc
$tertiary = aad0b2
$onTertiary = 153722
$tertiaryContainer = 75997e
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = fae287
$primaryFixedDim = ddc66e
$onPrimaryFixed = 221b00
$onPrimaryFixedVariant = 544600
$secondaryFixed = efe2bc
$secondaryFixedDim = d2c6a1
$onSecondaryFixed = 211b04
$onSecondaryFixedVariant = 4e462a
$tertiaryFixed = c5eccd
$tertiaryFixedDim = aad0b2
$onTertiaryFixed = 00210e
$onTertiaryFixedVariant = 2c4e37
$term0 = 353433
$term1 = bc8800
$term2 = e5cc47
$term3 = ffe496
$term4 = a8af6f
$term5 = d9a045
$term6 = d3cc74
$term7 = e2d7bf
$term8 = aba28f
$term9 = d99f00
$term10 = fadd3d
$term11 = fff3d8
$term12 = c4c397
$term13 = e8b768
$term14 = e8de79
$term15 = ffffff
$rosewater = fcf0e0
$flamingo = f4dfc0
$pink = ffd6a4
$mauve = ffad7f
$red = e6a93e
$maroon = e3b871
$peach = ecca7e
$yellow = fff0c8
$green = ece37d
$teal = e1e593
$sky = d5e28e
$sapphire = b3d27e
$blue = 75cf9d
$lavender = ffbcbb
$klink = 559652
$klinkSelection = 559652
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = b27f00
$knegativeSelection = b27f00
$kneutral = d5a300
$kneutralSelection = d5a300
$kpositive = b4ad00
$kpositiveSelection = b3ae00
$text = e9e2d4
$subtext1 = cdc6b4
$subtext0 = 979080
$overlay2 = 847d6e
$overlay1 = 706a5c
$overlay0 = 5e594c
$surface2 = 4d483c
$surface1 = 3b372d
$surface0 = 28251c
$base = 16130b
$mantle = 16130b
$crust = 15120a
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
