$primary_paletteKeyColor = 357f9b
$secondary_paletteKeyColor = 657a84
$tertiary_paletteKeyColor = 757498
$neutral_paletteKeyColor = 73787b
$neutral_variant_paletteKeyColor = 70787d
$background = 0f1417
$onBackground = dee3e6
$surface = 0f1417
$surfaceDim = 0f1417
$surfaceBright = 353a3d
$surfaceContainerLowest = 0a0f11
$surfaceContainerLow = 171c1f
$surfaceContainer = 1b2023
$surfaceContainerHigh = 262b2d
$surfaceContainerHighest = 303538
$onSurface = dee3e6
$surfaceVariant = 40484c
$onSurfaceVariant = c0c8cd
$inverseSurface = dee3e6
$inverseOnSurface = 2c3134
$outline = 8a9296
$outlineVariant = 40484c
$shadow = 000000
$scrim = 000000
$surfaceTint = 8ad0ee
$primary = 8ad0ee
$onPrimary = 003545
$primaryContainer = 004d63
$onPrimaryContainer = bce9ff
$inversePrimary = 0f6681
$secondary = b4cad5
$onSecondary = 1e333c
$secondaryContainer = 374c56
$onSecondaryContainer = d0e6f2
$tertiary = c5c3ea
$onTertiary = 2e2d4d
$tertiaryContainer = 8f8db2
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = bce9ff
$primaryFixedDim = 8ad0ee
$onPrimaryFixed = 001f29
$onPrimaryFixedVariant = 004d63
$secondaryFixed = d0e6f2
$secondaryFixedDim = b4cad5
$onSecondaryFixed = 081e27
$onSecondaryFixedVariant = 354a53
$tertiaryFixed = e2dfff
$tertiaryFixedDim = c5c3ea
$onTertiaryFixed = 191836
$onTertiaryFixedVariant = 444364
$term0 = 343434
$term1 = 8383ff
$term2 = 3fdfec
$term3 = 75fcdd
$term4 = 7bb2c6
$term5 = 7aaee9
$term6 = 83d6e6
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 51f2ff
$term11 = c9fff3
$term12 = a5c6d0
$term13 = a2c0f7
$term14 = 89eafa
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = dfe0f5
$pink = c4e0ff
$mauve = 7fc7ff
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d0f9f4
$green = 91eeff
$teal = a6eaff
$sky = a2e5ff
$sapphire = 7ed2f6
$blue = 6fc7f5
$lavender = 96d4fd
$klink = 1392bc
$klinkSelection = 1591bc
$kvisited = 0087cb
$kvisitedSelection = 0087cc
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bad1
$kpositiveSelection = 00bad2
$text = dee3e6
$subtext1 = c0c8cd
$subtext0 = 8a9296
$overlay2 = 787f83
$overlay1 = 656c70
$overlay0 = 545a5e
$surface2 = 43494d
$surface1 = 32383c
$surface0 = 212629
$base = 0f1417
$mantle = 0f1417
$crust = 0e1316
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
