$background = fffbff
$onBackground = 3a382b
$surface = fffbff
$surfaceDim = e8e3cf
$surfaceBright = fffbff
$surfaceContainerLowest = ffffff
$surfaceContainerLow = fef9eb
$surfaceContainer = f9f3e3
$surfaceContainerHigh = f3eedd
$surfaceContainerHighest = ede8d5
$onSurface = 3a382b
$surfaceVariant = ede8d5
$onSurfaceVariant = 676555
$outline = 848170
$outlineVariant = beb9a7
$inverseSurface = 0f0e08
$inverseOnSurface = a09d93
$shadow = 000000
$scrim = 000000
$surfaceTint = 6c6625
$primary = 6c6625
$primaryDim = 5f5a19
$onPrimary = ffffff
$primaryContainer = eee596
$onPrimaryContainer = 595313
$inversePrimary = f4eb9b
$primaryFixed = eee596
$primaryFixedDim = dfd789
$onPrimaryFixed = 464001
$onPrimaryFixedVariant = 635d1d
$secondary = 696547
$secondaryDim = 5d593c
$onSecondary = ffffff
$secondaryContainer = eae3be
$onSecondaryContainer = 565336
$secondaryFixed = eae3be
$secondaryFixedDim = dbd5b0
$onSecondaryFixed = 434025
$onSecondaryFixedVariant = 605c3f
$tertiary = 815e2c
$tertiaryDim = 735221
$onTertiary = ffffff
$tertiaryContainer = fbcd90
$onTertiaryContainer = 624313
$tertiaryFixed = fbcd90
$tertiaryFixedDim = ecbf84
$onTertiaryFixed = 4c3002
$onTertiaryFixedVariant = 6d4c1c
$error = ae4025
$errorDim = 791903
$onError = ffffff
$errorContainer = fd795a
$onErrorContainer = 6e1400
$primaryPaletteKeyColor = 7f7936
$secondaryPaletteKeyColor = 7c7858
$tertiaryPaletteKeyColor = 95703c
$neutralPaletteKeyColor = 7a776e
$neutralVariantPaletteKeyColor = 7a7767
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 7f7936
$secondary_paletteKeyColor = 7c7858
$tertiary_paletteKeyColor = 95703c
$neutral_paletteKeyColor = 7a776e
$neutral_variant_paletteKeyColor = 7a7767
$term0 = 9d9a95
$term1 = 7b5c00
$term2 = 838500
$term3 = 876d00
$term4 = 978a20
$term5 = 8b6300
$term6 = 71883c
$term7 = 27211d
$term8 = 0f0f0e
$term9 = 987200
$term10 = a4a52b
$term11 = a68817
$term12 = bcad41
$term13 = ad7b00
$term14 = 90a958
$term15 = 2e2723
$rosewater = 957a2c
$flamingo = 937100
$pink = a47500
$mauve = 8f3b00
$red = 6a5100
$maroon = 7f6100
$peach = 8e7300
$yellow = 927d00
$green = 707400
$teal = 5a7024
$sky = 4b882e
$sapphire = 607c2b
$blue = 00664e
$lavender = 00816c
$klink = 559652
$klinkSelection = 559652
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = aa8200
$knegativeSelection = aa8200
$kneutral = cba700
$kneutralSelection = cca700
$kpositive = a6b112
$kpositiveSelection = a6b112
$text = 3a382b
$subtext1 = 676555
$subtext0 = 848170
$overlay2 = 939082
$overlay1 = a3a096
$overlay0 = b4b0aa
$surface2 = c5c1be
$surface1 = d7d3d2
$surface0 = ebe7e9
$base = fffbff
$mantle = f6f3f6
$crust = f1edef
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
