# 该文件用于指定快捷键不被抑制

bind = $kbWindowFullscreen, fullscreen, 0 # 浮动模式全屏
bind = $kbWindowBorderedFullscreen, fullscreen, 1  # 平铺模式全屏
# 快捷键速查表
bind = $cheatsheet, exec, touch /tmp/cheatsheet_toggle
# 强制关闭窗口
bind = $kbCloseWindow, killactive,

# 媒体与硬件控制
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindle = , XF86AudioRaiseVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ $volumeStep%+
bindle = , XF86AudioLowerVolume, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ 0; wpctl set-volume @DEFAULT_AUDIO_SINK@ $volumeStep%-
bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown
