# =========================================
#  基础路径配置
# =========================================
music_directory    "~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
log_file           "syslog"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

# =========================================
#  连接与更新设置
# =========================================
#bind_to_address    "127.0.0.1"
#port               "6600"
bind_to_address    "/tmp/socket"

auto_update        "yes"
restore_paused     "yes"

# =========================================
#  核心音质优化 
# =========================================

# 重采样配置
resampler {
  plugin "soxr"
}

# 禁用软件音量 (建议由 rmpc/pipewire 控制总音量)
mixer_type         "software"

# =========================================
#  音频输出
# =========================================

# 主音频输出 (PipeWire 原生 + 锁频)
audio_output {
        type            "pipewire"
        name            "PipeWire Sound Server"
        # 强制输出 48kHz / 32位浮点 / 双声道
        format          "48000:32:2"
}

# 可视化输出 (Cava)
audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "48000:16:2"
}
